#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  cd "$shome"
  exec pipenv run python "$shome/exec/kmsauth-validate.py" "$@"
}

source sub "$BASH_SOURCE" "$@"
