#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_kmsauth="0.0.1"
  jq -n --arg kmsauth "$ver_kmsauth" '{kmsauth: $kmsauth}'
}

version "$@"
